### ISSUE TITLE
About the data for R

### ISSUE THREAD

**Issue by mehmetumutmutlu** [cldf/cookbook#19]
The data which is imported on R scripts is different from the one on the web service (wals.info). For example, it has more languages. Is it updated?

`"https://cdstar.shh.mpg.de/bitstreams/EAEA0-7269-77E5-3E10-0/wals_dataset.cldf.zip"`

**Comment by xrotwang** [comment]
Yes, WALS Online does get updated occassionally. It's best to access a particular version from here: https://github.com/cldf-datasets/wals/releases
