### ISSUE TITLE
CLDF with spreadsheet software

### ISSUE THREAD

**Issue by chrzyki** [cldf/cookbook#8]
Prepare a tutorial for working with CLDF in 'plain' spreadsheet software (e.g. Excel, Calc, etc.).

Things to consider:

- joining tables in spreadsheet software
- @Anaphory [template](https://github.com/lessersunda/LanguageTemplate) for creating word lists
- visidata
- CLDF metadata in spreadsheet software

**Comment by xrotwang** [comment]
Use cases to address:

(1) I am a field linguist with a spreadsheet of words and their meanings
that I collected long ago. I would like to make the data available for
re-use by adopting the CLDF format. Where do I start?

(2) I am an expert on languages of a particular region/linguistic
family. I have a spreadsheet in which rows are languages, columns are
concepts, and cells contain the word for concept X in language Y. I
would to make these data available for reuse by ensuring they follow the
CLDF format. Where do I start?

**Comment by chrzyki** [comment]
Closed in https://github.com/cldf/cookbook/commit/cc55e372d9a3c4c0d3e4151cd97273af5af5d044 and https://github.com/cldf/cookbook/commit/a8016e038b1e4cf8ea90317951cc134d35ed3a6e.
