### ISSUE TITLE
Excel-to-CLDF blog post: How to make cookbook benefit?

### ISSUE THREAD

**Issue by Anaphory** [cldf/cookbook#9]
I have written a blog post (https://calc.hypotheses.org/803) which describes a similar case to the existing recipe in https://github.com/cldf/cookbook/tree/master/recipes/excel#a-more-advanced-example, with Python code and examples in https://github.com/Anaphory/matrix_to_beastling. I would be happy to re-use it to make the cookbook better by providing other ways to do things, how should I do that?

**Comment by xrotwang** [comment]
@chrzyki any ideas? Maybe we can talk about this as well end of November in Jena?

**Comment by chrzyki** [comment]
Cool! Yeah a) talking about that in November would be good b) @Anaphory do you have an specific data/scenario in mind?

**Comment by Anaphory** [comment]
My specific scenario is described in https://calc.hypotheses.org/803: Yunus Sulistyono, a PhD student colleague of mine, has collected data on 13 Alorese [alor1247] dialects and wants me to run a Beastling-driven Bayesian inference on them.

**Comment by Anaphory** [comment]
(Talking about it in 10-or-so days is obviously a good idea.)

**Comment by chrzyki** [comment]
Ah, okay, thanks! Will have a closer look at the blog post!

**Comment by LinguList** [comment]
What about re-organizing the cookbook a bit in the form of linking blog-posts as well? In my experience, rather than writing a markdown file alone, people may prefer writing a blogpost. Ideal would be a combination, as we did with clics: https://calc.hypotheses.org/384

**Comment by xrotwang** [comment]
See #16
